# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57a6dd75c92142078d8297bcb899c959021228376d6775acdfa1dafcc55b8f7adb1379b9386622e4b56b26140ee50a5d1e04c814cb1a8b1a98ac5a5c3bba4bf7

test:
  secret_key_base: 6694e0bf6b7ab09cafe1a96b528b5d6265aec5740962a171c3865459338d651c237dd8b5fb946fe6b1bc795253133d5439a8150812cd7dc59d1d642cede3928b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
